package jpa.repositories;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;

public class AppJpaTest {

    @Test
    public void testAppHasAGreeting() {

    }
}
